use_gpu: True
device: 0
early_stop:
  patience: 5
federate:
  mode: standalone
  standalone_args :
    use_shadow : True
    shadow_client_num : 30
    use_one_hop_eval : True
  method : FedAvg
  sampler : uniform
  total_round_num: 20000
  client_num: 16 #22363
  sample_client_num: 16
  sample_client_rate: -1.0
  make_global_eval : False 
data:
  root: ../../../../data1/donghoon/FederatedScopeData/Amazon_Sports_and_Outdoors_5core_mapped
  type: sr_data
  df_path: ../../../../data1/donghoon/FederatedScopeData/Amazon_Sports_and_Outdoors_5core_mapped/inter.csv
  consistent_label_distribution: True
  
  partitioned_df_path: ../../../../data1/donghoon/FederatedScopeData/Amazon_Sports_and_Outdoors_5core_mapped/split
  save_partitioned_df_path: ../../../../data1/donghoon/FederatedScopeData/Amazon_Sports_and_Outdoors_5core_mapped/split
  
  min_sequence_length: 5
  max_sequence_length: 50
  user_num: 35598
  item_num: 532197

  splitter : sr_splitter
dataloader :
  type : base
  batch_size : 1
model:
  type: sasrec
  hidden_dropout_prob: 0.0
  attn_dropout_prob: 0.0
  hidden_size : 64
  item_num : 532197
train:
  batch_or_epoch : 'epoch'
  local_update_steps: 20
  optimizer:
    lr: 0.01
criterion:
  type: hinge
trainer:
  type: sasrec_trainer
eval:
  freq: 1
  metrics: ['recall_10','ndcg_10'] #'recall_20','ndcg_10','ndcg_20']
  split : ['val', 'test']
  best_res_update_round_wise_key: test_avg_loss
  count_flops: False