use_gpu: False
device: 0
early_stop:
  patience: 100
federate:
  mode: standalone
  total_round_num: 10
  client_num: 100
  sample_client_num: 10
  sample_client_rate: -1.0
data:
  root: ../../../../data1/donghoon/FederatedScopeData/ml-1m/
  type: sr_data
  consistent_label_distribution: True
dataloader :
  type : base
  batch_size : 1
model:
  type: sasrec
train:
  local_update_steps: 50
  optimizer:
    lr: 1.
criterion:
  type: CrossEntropyLoss
trainer:
  type: sasrec_trainer
eval:
  freq: 1
  metrics: ['recall_10','recall_20','ndcg_10','ndcg_20']
  split : ['val', 'test']
  best_res_update_round_wise_key: test_avg_loss
  count_flops: False