use_gpu: True
device: 1
early_stop:
  patience: 5
federate:
  mode: standalone
  method : FedAvg
  total_round_num: 200
  client_num: 6040
  sample_client_num: 1
  sample_client_rate: -1.0
  make_global_eval : True # without it it would be too slow
data:
  root: ../../../../data1/donghoon/FederatedScopeData/ml-1m/
  type: sr_data
  consistent_label_distribution: True
dataloader :
  type : base
  batch_size : 1
model:
  type: sasrec
train:
  local_update_steps: 1
  optimizer:
    lr: 0.001
criterion:
  type: CrossEntropyLoss
trainer:
  type: sasrec_trainer
eval:
  freq: 1
  metrics: ['recall_10','recall_20','ndcg_10','ndcg_20']
  split : ['val', 'test']
  best_res_update_round_wise_key: test_avg_loss
  count_flops: False