use_gpu: True
device: 0
early_stop:
  patience: 5
aggregator:
  BFT_args: {}
  byzantine_node_num: 0
  num_agg_groups: 1
  robust_rule: fedavg
federate:
  mode: standalone
  method : sybil_attack
  total_round_num: 200
  client_num: 6040 # 6040
  sample_client_num: 200
  sample_client_rate: -1.0
  make_global_eval : True # without it it would be too slow
data:
  root: ../../../../data1/donghoon/FederatedScopeData/ml-1m/
  type: sr_data
  consistent_label_distribution: True
dataloader :
  type : base
  batch_size : 1
model:
  type: sasrec
train:
  local_update_steps: 60
  optimizer:
    lr: 0.001
criterion:
  type: CrossEntropyLoss
trainer:
  type: sasrec_trainer
eval:
  freq: 20
  metrics: ['recall_10','recall_20','ndcg_10','ndcg_20','poison_recall_10','poison_ndcg_10','poison_recall_20','poison_ndcg_20','poison_recall_50','poison_ndcg_50']
  split : ['val', 'test']
  best_res_update_round_wise_key: test_avg_loss
  count_flops: False
attack :
  attack_method : 'sr_targeted_segment_sasrec'
  attacker_id : []
  segment_item_ids : [2858, 260, 1196, 1210, 480, 2028, 589, 2571, 1270, 593, 1580, 1198, 608, 2762, 110, 2396, 1197, 527, 1617, 1265]
  target_item_id : 2308
  covisitation : True