use_gpu: True
device: 3
early_stop:
  patience: 5
federate:
  mode: standalone
  method : FedAvg
  total_round_num: 200
  client_num: 6040 # 6040
  sample_client_num: 200
  sample_client_rate: -1.0
  make_global_eval : False # without it it would be too slow
aggregator :
  robust_rule : krum
  byzantine_node_num : 50
  BFT_args :
    krum_agg_num : 1
outdir: exp/krum_sasrec_on_sr_data_lr0.001_lstep60
data:
  root: ../../../../data1/donghoon/FederatedScopeData/ml-1m/
  type: sr_data
  consistent_label_distribution: True
dataloader :
  type : base
  batch_size : 1
model:
  type: sasrec
train:
  local_update_steps: 60
  optimizer:
    lr: 0.001
criterion:
  type: CrossEntropyLoss
trainer:
  type: sasrec_trainer
eval:
  freq: 20
  metrics: ['recall_10','recall_20','ndcg_10','ndcg_20','poison_recall_10','poison_ndcg_10','poison_recall_20','poison_ndcg_20','poison_recall_50','poison_ndcg_50']
  split : ['val', 'test']
  best_res_update_round_wise_key: test_avg_loss
  count_flops: False
attack :
  attack_method : 'sr_targeted_labelflip_sasrec'
  attacker_id : [12, 206, 214, 287, 388, 539, 555, 842, 871, 1457, 1523, 1580, 1772, 1833, 2089, 2137, 2165, 2260, 2478, 2689, 2807, 2873, 2878, 3228, 3233, 3322, 3332, 3645, 3830, 3884, 4120, 4176, 4227, 4362, 4481, 4598, 4721, 4792, 4894, 4945, 5009, 5045, 5453, 5506, 5658, 5663, 5761, 5815, 5885, 5974]
  target_item_id : 2308