use_gpu: True
device: 0
early_stop:
  patience: 1000
federate:
  mode: standalone
  method : shadow_with_aug_selection
  total_round_num: 30000
  client_num: 16 # 6040
  sample_client_num: 16
  sample_client_rate: -1.0
  make_global_eval : True
  save_to: "../../../../data1/donghoon/FederatedScopeData/exp/ml-1m/0923_Augmentation_Selection_MAB_alpha-25e-1.pt"
  standalone_args :
    use_shadow : True
    shadow_client_num : 6040
    use_one_hop_eval : True
data:
  root: ../../../../data1/donghoon/FederatedScopeData/ml-1m/
  partitioned_df_path : '../../../../data1/donghoon/FederatedScopeData/ml-1m/combined'
  type: sr_data
  consistent_label_distribution: False ## This can be only used when the datasets are sorted by user_ids
  splitter : sr_splitter
  augmentation_args :
    augmentation_column : 'augmentation_idx:token'
    use_augmentation : True
    max_augmentation_idx : 9 ## load all augmentations
    is_zero_original : False
    is_multiple : True
    aug_types_count : 9 ## aug types
    df_paths : ['../../../../data1/donghoon/FederatedScopeData/ml-1m/split',
                '../../../../data1/donghoon/FederatedScopeData/ml-1m/self_sampled_pushing_left_10_20_no_original',
                '../../../../data1/donghoon/FederatedScopeData/ml-1m/random_pushing_left_10_20_no_original',
                '../../../../data1/donghoon/FederatedScopeData/ml-1m/random_replacing_0.1_no_original',
                '../../../../data1/donghoon/FederatedScopeData/ml-1m/random_replacing_0.2_no_original',
                '../../../../data1/donghoon/FederatedScopeData/ml-1m/random_replacing_0.3_no_original',
                '../../../../data1/donghoon/FederatedScopeData/ml-1m/random_replacing_0.4_no_original',
                '../../../../data1/donghoon/FederatedScopeData/ml-1m/random_replacing_0.5_no_original',
                '../../../../data1/donghoon/FederatedScopeData/ml-1m/shuffle_no_original'
                ]
  augmentation_controller :
    type : 'mab' ## 'mab', 'epsilon_greedy', 'thompson', 'sliding_window', 'mdp'
    args : 
      decay_rate : 0.99
      alpha : 2.5
      epsilon : 0.1
      window_size : 100
      lr : 0.01
      gamma : 0.9
dataloader :
  type : base
  batch_size : 1
model:
  type: sasrec
  hidden_dropout_prob: 0.0
  attn_dropout_prob: 0.0
  pretrained_model_path : ""
  hidden_size: 64
train:
  batch_or_epoch : 'batch'
  local_update_steps: 20
  optimizer:
    lr: 0.001
criterion:
  type: CrossEntropyLoss
trainer:
  type: sasrec_trainer
eval:
  freq: 1000
  metrics: ['recall_10','recall_20','ndcg_10','ndcg_20']
  split : ['val', 'test']
  best_res_update_round_wise_key: test_avg_loss
  count_flops: False
