use_gpu: True
device: 0
early_stop:
  patience: 5
federate:
  mode: standalone
  method : FedAvg
  total_round_num: 2500
  client_num: 6040 # 6040
  sample_client_num: 16
  sample_client_rate: -1.0
  make_global_eval : False 
data:
  root: ../../../../data1/donghoon/FederatedScopeData/ml-1m/
  partitioned_df_path : '../../../../data1/donghoon/FederatedScopeData/ml-1m/random_augmented_0.5'
  type: sr_data
  consistent_label_distribution: True
  splitter : sr_splitter
  augmentation_column : 'augmentation_idx:token'
  use_augmentation : True
  max_augmentation_idx : 10 ## 1 + 10 augmentations
dataloader :
  type : base
  batch_size : 1
model:
  type: sasrec
  hidden_dropout_prob: 0.0
  attn_dropout_prob: 0.0
train:
  batch_or_epoch : 'epoch'
  local_update_steps: 1
  optimizer:
    lr: 0.001
criterion:
  type: CrossEntropyLoss
trainer:
  type: sasrec_trainer
eval:
  freq: 100
  metrics: ['recall_10','recall_20','ndcg_10','ndcg_20']
  split : ['val', 'test']
  best_res_update_round_wise_key: test_avg_loss
  count_flops: False
