use_gpu: True
device: 0
early_stop:
  patience: 1000
federate:
  mode: standalone
  method : shadow
  unseen_clients_rate : 0.5
  total_round_num: 40000
  client_num: 16 # 6040
  sample_client_num: 16
  sample_client_rate: -1.0
  make_global_eval : True
  save_to: "../../../../data1/donghoon/FederatedScopeData/exp/ml-1m_hidden_64_lr1e-2/1027_step_20_unseen_5e-1_No_Augs.pt"
  standalone_args :
    use_shadow : True
    shadow_client_num : 6040
    use_one_hop_eval : True
aggregator:
  robust_rule : fedavg_variance
data:
  root: ../../../../data1/donghoon/FederatedScopeData/ml-1m/
  partitioned_df_path : '../../../../data1/donghoon/FederatedScopeData/ml-1m/split'
  type: sr_data
  consistent_label_distribution: False
  splitter : sr_splitter
dataloader :
  type : base
  batch_size : 1
model:
  type: sasrec
  hidden_dropout_prob: 0.0
  attn_dropout_prob: 0.0
  pretrained_model_path : '../../../../data1/donghoon/FederatedScopeData/exp/ml-1m_hidden_64_lr1e-2/1027_step_20_unseen_5e-1_No_Augs/checkpoint_round_23000.pt'
  checkpoint_round: 23000
  hidden_size: 64
train:
  batch_or_epoch : 'batch'
  local_update_steps: 20
  optimizer:
    lr: 0.01
criterion:
  type: CrossEntropyLoss
trainer:
  type: sasrec_trainer
eval:
  freq: 1000
  metrics: ['recall_10','recall_20','ndcg_10','ndcg_20']
  split : ['val', 'test']
  best_res_update_round_wise_key: test_avg_loss
  count_flops: False
