use_gpu: True
device: 1
early_stop:
  patience: 5
federate:
  mode: standalone
  method : shadow
  total_round_num: 15000
  client_num: 16 # 6040
  sample_client_num: 16
  sample_client_rate: -1.0
  make_global_eval : False
  save_to: "../../../../data1/donghoon/FederatedScopeData/exp/ml-1m/0823_cut_from_left_plus_random_20_augs_15K.pt"
  standalone_args :
    use_shadow : True
    shadow_client_num : 6040
    use_one_hop_eval : True
data:
  root: ../../../../data1/donghoon/FederatedScopeData/ml-1m/
  partitioned_df_path : '../../../../data1/donghoon/FederatedScopeData/ml-1m/random_plus_cut_from_left'
  type: sr_data
  consistent_label_distribution: False
  splitter : sr_splitter
  augmentation_column : 'augmentation_idx:token'
  use_augmentation : True
  max_augmentation_idx : 20 ## 1 + 20 augmentations
dataloader :
  type : base
  batch_size : 1
model:
  type: sasrec
  hidden_dropout_prob: 0.0
  attn_dropout_prob: 0.0
  pretrained_model_path : ""
train:
  batch_or_epoch : 'epoch'
  local_update_steps: 1
  optimizer:
    lr: 0.001
criterion:
  type: CrossEntropyLoss
trainer:
  type: sasrec_trainer
eval:
  freq: 250
  metrics: ['recall_10','recall_20','ndcg_10','ndcg_20']
  split : ['val', 'test']
  best_res_update_round_wise_key: test_avg_loss
  count_flops: False