use_gpu: True
device: 1
early_stop:
  patience: 1000
federate:
  mode: standalone
  method : shadow
  standalone_args :
    use_shadow : True
    shadow_client_num : 22363
    use_one_hop_eval : True
  sampler : uniform
  total_round_num: 30000
  client_num: 16 #22363
  sample_client_num: 16
  sample_client_rate: -1.0
  make_global_eval : True
  save_to : "../../../../data1/donghoon/FederatedScopeData/exp/amazon_beauty/0909_pretrained_randReplace1e-1_to_orginal.pt"
data:
  root: ../../../../data1/donghoon/FederatedScopeData/Amazon_Beauty_5core
  type: sr_data
  df_path: ../../../../data1/donghoon/FederatedScopeData/Amazon_Beauty_5core/inter.csv
  consistent_label_distribution: False
  partitioned_df_path: ../../../../data1/donghoon/FederatedScopeData/Amazon_Beauty_5core/split
  save_partitioned_df_path: ../../../../data1/donghoon/FederatedScopeData/Amazon_Beauty_5core/split
  min_sequence_length: 5
  max_sequence_length: 50
  user_num: 22363
  item_num: 12101
  splitter : sr_splitter
dataloader :
  type : base
  batch_size : 1
model:
  type: sasrec
  hidden_dropout_prob: 0.0
  attn_dropout_prob: 0.0
  hidden_size : 64
  item_num : 12101
  pretrained_model_path : "../../../../data1/donghoon/FederatedScopeData/exp/amazon_beauty/0906_random_replacing_1e-1.pt"
train:
  batch_or_epoch : 'batch'
  local_update_steps: 20
  optimizer:
    lr: 0.01
criterion:
  type: CrossEntropyLoss
trainer:
  type: sasrec_trainer
eval:
  freq: 1000
  metrics: ['recall_10','recall_20','ndcg_10','ndcg_20']
  split : ['val', 'test']
  best_res_update_round_wise_key: test_avg_loss
  count_flops: False